from __future__ import annotations

import discord
from discord.ext import commands
from discord_slash import cog_ext, SlashContext
from discord_slash.utils.manage_components import create_button, create_actionrow, wait_for_component
from discord_slash.model import ButtonStyle


from utils import cmdlogger


async def infemb(message) -> None:
	infembed = discord.Embed(
		title="Information about levels",
		description="General Information: \nThese levels can be generated by different users, and playable by different users. \nIt uses the format shown below!",
		color=0x98C9F1
	)
	infembed.add_field(
		name="Regular Blocks:",
		value="Regular blocks can be signified with the ```ansi\n[0;34;40m Capital Letter [1;40;34mB``` Regular blocks can act as platforms."
	)
	infembed.add_field(
		name="Spikes:",
		value="Spikes can be signified with the ```ansi\n[0;34;40m Capital Letter [1;40;34mS``` Spikes can hurt/kill players."
	)
	infembed.add_field(
		name="Air:",
		value="Air can be signified with ```ansi\n[0;34;40m Capital Letter [1;40;34mA``` Air is a block that players can walk through.",
		inline=False
	)
	infembed.add_field(
		name="Layers:",
		value="New layers can be signified with ```ansi\n[0;34;40m Capital Letter [1;40;34mN``` New layers can be used to add more room to your levels."
	)

	await message.edit(embed=infembed, components=[])
	return


class Gen(commands.Cog):
	def __init__(self, bot) -> None:
		self.bot: commands.Bot = bot
	
	@cog_ext.cog_slash(name='levels',description='Generate or play a level!',guild_ids=[566694134212198481])
	async def levels(self,ctx:SlashContext, level = None, create = None):
		await ctx.defer()
		if not level and not create:
			infbtn = create_actionrow(
				*[
					create_button(
						style=ButtonStyle.blue,
						emoji="👷",
						custom_id="i",
						disabled=False),
					create_button(
						style=ButtonStyle.green,
						emoji="🛠️",custom_id="l")
				]
			)
			message = await ctx.send(
				"You have not provided a level id or have not created a level! If you need information on how to create a level, please click the 👷 button! \nIf you want a list of other existing levels click the 🛠️ button.",
				components=[infbtn]
			)
			button_ctx = await wait_for_component(client=self.bot, components=infbtn)

			if button_ctx.custom_id == "i":
				await infemb(message)

			if button_ctx.custom_id == "l":
				# await lvlemb(ctx,message,infbtn)
				await message.edit(content="Levels")

		if not create:
			await ctx.send(level)
		
		
def setup(bot: commands.Bot):
	cmdlogger.info("Loading Gen")
	bot.add_cog(Gen(bot))
